### ISSUE TITLE
AWS provider configuration is overriden

### ISSUE THREAD

**Issue by mosheavni** [sysdiglabs/terraform-aws-secure-for-cloud#33]
I installed the example module (on the UI's getting started page, that's the suggested method) with my own provider:
```
provider "aws" {
  region = "us-east-2"
  profile = "dev"
}
```
But since the module defines its own provider, it overrides mine and uses the default profile, with the region being what is defined in `var.region`.
This is an anti-behavior of terraform modules, please consider removing the provider block:
https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/5fd212bfff5cf444913cc29727b3e14586b53ab2/examples/single-account/main.tf#L1-L3
![image](https://user-images.githubusercontent.com/17252601/138691994-2434d61a-5a60-48ca-8c65-03ba54b3249d.png)

**Comment by wideawakening** [comment]
that makes sense @mosheavni, we will look into it!

hope this was not a stopper;  examples are just guidelines/building blocks for module usage, but if you want to take advantage from them, given your snippet, you can always export `AWS_PROFILE` to select the desired profile.

**Comment by mosheavni** [comment]
### 

> that makes sense @mosheavni, we will look into it!
> 
> hope this was not a stopper; examples are just guidelines/building blocks for module usage, but if you want to take advantage from them, given your snippet, you can always export `AWS_PROFILE` to select the desired profile.

Sure but that feels quite "hackish".
Terraform modules should work out of the box, especially when they are in your official documentation on the "Getting Started" page.

Assembling the pieces (ECS cluster, S3 buckets, SSM params, IAM policies, etc...) to make the whole thing work is possible but does require some work.
