### ISSUE TITLE
Dangerous/broad policy attached to ECS tasks

### ISSUE THREAD

**Issue by r2bit** [sysdiglabs/terraform-aws-secure-for-cloud#54]
We noticed a suspicious policy attached to `cloud-connector` ECS task role:
https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/bdd8505043e7195b318bf2fc360ad0c959329c79/modules/services/cloud-connector/ecs-service-security.tf#L106-L121

Essentially granting access to all secrets in an account (or something close to that?). 
Given the danger such policy poses, is there a specific reason that access is required by `cloud-connector`? Meanwhile, we're forced to use our own local copy of `modules/services/cloud-connector` which simply excludes the problematic blocks. :(

**Comment by wideawakening** [comment]
no reason at all, we've been pinning down permissions and this is one slipped; we can pin it down to the specific secret ecs is handling for cloud-connector. 
will take care of it!

**Comment by wideawakening** [comment]
will try to push this soon, but if you wanna share your local changes, glad to merge the PR

**Comment by r2bit** [comment]
> will try to push this soon, but if you wanna share your local changes, glad to merge the PR

What we did right now was simply remove that policy entirely. Since there actually _is_ a secret ECS has to manage, I suggest you create a PR this time. We can help with next ones. ;)

**Comment by wideawakening** [comment]
> What we did right now was simply remove that policy entirely. Since there actually _is_ a secret ECS has to manage, I suggest you create a PR this time. We can help with next ones. ;)

umm but, if you removed policy, not sure how is it working (permission is required for task to fetch secret).
did you maybe provision specific permissions out of IAC  or other way?

**Comment by r2bit** [comment]
> > What we did right now was simply remove that policy entirely. Since there actually _is_ a secret ECS has to manage, I suggest you create a PR this time. We can help with next ones. ;)
> 
> umm but, if you removed policy, not sure how is it working (permission is required for task to fetch secret). did you maybe provision specific permissions out of IAC or other way?

As far as I know the token is stored in AWS System Manager (actions `ssm:*`) not AWS Secrets Manager (actions `secretsmanager:*`).

**Comment by wideawakening** [comment]
my bad meant
```
< permission is required for task to fetch secret
> permission for ecs task to be able to get/decrypt the cloudtrail-kms secret key
```
https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/master/modules/infrastructure/cloudtrail/kms.tf

either-way, we should be able to pin it down to the specific

**Comment by r2bit** [comment]
> my bad meant
> 
> ```
> < permission is required for task to fetch secret
> > permission for ecs task to be able to get/decrypt the cloudtrail-kms secret key
> ```
> 
> https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/master/modules/infrastructure/cloudtrail/kms.tf
> 
> either-way, we should be able to pin it down to the specific

Oh, sorry. We're using our existing CloudTrail. That's why it worked then, I guess.

**Comment by r2bit** [comment]
@wideawakening we ended up switching back to a local trail and I made a fix for the policy in our fork. I didn't create a PR here, since I'm not quite sure what's the purpose of having `secretsmanager:*` privileges. 
You can see the last two commits here: https://github.com/salemove/terraform-aws-secure-for-cloud/tree/fix_kms_privileges. It's working w/o problems for us right now.

**Comment by wideawakening** [comment]
@r2bit  we addressed this issue and you were right, we neither knew what `secretmanager:*`was required for.. sorry for those broad unnecessary privileges. 
fixes on next release
