### ISSUE TITLE
Fix Public Key permission

### ISSUE THREAD

**Issue by ftzimmer** [sysdiglabs/terraform-aws-secure-for-cloud#75]
Hello team. 
This is critical. It's providing full access to the public to this key. It has to be limited at minimum to the owner account

https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/f1e6c53c4a7899aed8a872c84bab9f3f7c8579dd/modules/infrastructure/cloudtrail/kms.tf#L24

**Comment by ftzimmer** [comment]
Made a PR to fix it
https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/pull/76

**Comment by wideawakening** [comment]
thx for the push there @ftzimmer , we will go through those kms permissions deeper. 
they should be pinned to that specific resource and disallow other existing * principal.

**Comment by Chili-Man** [comment]
@wideawakening any update on getting the fix merged in?

**Comment by ftzimmer** [comment]
Indeed, would be great to limit even more, but if that's not happening soon, it's better to push a simple update on the meantime.

**Comment by wideawakening** [comment]
on backlog already.

if you check the current key policies (with all the statements that are more pinned) seems like the statement pointed out is a very general one, so my thoughts are that it was a first approach for the organizational, cross-account setup. let us give it a proper pin and test 🙏🏽
