### ISSUE TITLE
Inherit 'name' from Cloud Connector ECS in the cloud bench module

### ISSUE THREAD

**Issue by e-minguez** [sysdiglabs/terraform-aws-secure-for-cloud#98]
https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/blob/4683e4dd03deef294f9f2c4da9714af966eac9d9/modules/services/cloud-bench/main.tf#L55

https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/tree/master/modules/services/cloud-connector-ecs#input_name allows you to specify a name for subresources created as part of the plan, otherwise it fails with:

```
task with this name already exists: timestamp=2022-06-08T16:02:53.425+0200
2022-06-08T16:02:53.480+0200 [ERROR] vertex "module.secure-for-cloud_example_single-account.module.cloud_bench[0].sysdig_secure_benchmark_task.benchmark_task" error: 400 Bad Request
```

By modifying the name manually I've been able to create another benchmark:
![image](https://user-images.githubusercontent.com/346758/172640019-657349ab-98f6-4f13-87de-27407dbb766e.png)

**Comment by wideawakening** [comment]
thx @e-minguez, hope it serves to alleviate testing
